server:
  port: 5000

spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 10


mybatis-plus:
  basePackages: com.yufenghui.tdd.springboot.**.mapper
